/**
 * Resilient loader for the generated `reports/outdated-pins.md` artifact.
 *
 * `reports/` is gitignored — it only exists after `bun run deps:outdated` runs
 * (locally or in the weekly audit workflow). Production builds must therefore
 * treat the report as OPTIONAL:
 *
 *  - `import.meta.glob` (not a static `?raw` import) so an absent file resolves
 *    to `{}` instead of failing the Vite/Worker build with
 *    "Could not load .../reports/outdated-pins.md?raw".
 *  - the glob call itself is wrapped, so an unreadable/garbled module still
 *    yields a status instead of throwing during module evaluation (which would
 *    take down SSR for the whole route).
 *
 * Consumers render a clear fallback message for anything other than "ok".
 */

export type ReportSourceStatus = "ok" | "missing" | "unreadable";

export interface ReportSource {
  status: ReportSourceStatus;
  /** Raw markdown; empty string for missing/unreadable reports. */
  source: string;
}

export const REPORT_PATH = "reports/outdated-pins.md";

export const REPORT_FALLBACK: Record<
  Exclude<ReportSourceStatus, "ok">,
  { label: string; detail: string }
> = {
  missing: {
    label: "No audit report in this build",
    detail: `${REPORT_PATH} is generated by the weekly dependency audit and is not committed to the repository, so this build has no report to render. Numbers below stay empty until the next audit publishes one — nothing is wrong with your pins.`,
  },
  unreadable: {
    label: "Audit report could not be read",
    detail: `${REPORT_PATH} was found but could not be read as text, so it has been ignored. Re-run the dependency audit to regenerate a clean report.`,
  },
};

function readGlob(): ReportSource {
  try {
    const modules = import.meta.glob("../../reports/outdated-pins.md", {
      query: "?raw",
      import: "default",
      eager: true,
    }) as Record<string, unknown>;

    const values = Object.values(modules);
    if (values.length === 0) return { status: "missing", source: "" };

    const raw = values[0];
    if (typeof raw !== "string" || raw.trim() === "") {
      return { status: "missing", source: "" };
    }
    return { status: "ok", source: raw };
  } catch {
    return { status: "unreadable", source: "" };
  }
}

export const reportSource: ReportSource = readGlob();
