import { createFileRoute } from "@tanstack/react-router";
import { useMemo } from "react";
import {
  currentPercent,
  groupByBump,
  healthPosture,
  parseDependencyHealth,
  reportAge,
  type BumpKind,
} from "@/lib/dependency-health";
import { ROUTES } from "@/lib/routes";
import { AppLink } from "@/components/AppLink";

// reports/ is gitignored (generated by scripts/check-outdated-pins.ts), so the
// file may be absent at build time. import.meta.glob resolves to {} instead of
// failing the build, and the page renders its empty state.
const reportModules = import.meta.glob("../../reports/outdated-pins.md", {
  query: "?raw",
  import: "default",
  eager: true,
}) as Record<string, string>;
const reportSource = Object.values(reportModules)[0] ?? "";

const REPO = "https://github.com/resonance36912-cell/resonance-hub";
const TITLE = "Dependency Health — Resonance Hub";
const DESCRIPTION =
  "Live view of every exact dependency pin in the Resonance Hub: how many are major, minor, or patch releases behind, straight from the weekly audit report.";

export const Route = createFileRoute("/dependency-health")({
  head: () => ({
    meta: [
      { title: TITLE },
      { name: "description", content: DESCRIPTION },
      { property: "og:title", content: TITLE },
      { property: "og:description", content: DESCRIPTION },
      { property: "og:type", content: "website" },
      { property: "og:site_name", content: "Reson8.life" },
      { property: "og:url", content: "https://reson8.life/dependency-health" },
      { name: "twitter:card", content: "summary" },
      { name: "twitter:title", content: TITLE },
      { name: "twitter:description", content: DESCRIPTION },
    ],
    links: [
      { rel: "canonical", href: "https://reson8.life/dependency-health" },
    ],
  }),
  component: DependencyHealthPage,
});

const BUMP_TONE: Record<BumpKind, string> = {
  major: "text-rose-300 border-rose-400/40 bg-rose-400/10",
  minor: "text-sky-300 border-sky-400/40 bg-sky-400/10",
  patch: "text-emerald-300 border-emerald-400/40 bg-emerald-400/10",
  prerelease: "text-amber-300 border-amber-400/40 bg-amber-400/10",
};

const BUMP_BLURB: Record<BumpKind, string> = {
  major: "New major version — may contain breaking changes. Reviewed by hand.",
  minor: "Backwards-compatible features. Included in the automated update PR.",
  patch: "Bug and security fixes only. Included in the automated update PR.",
  prerelease: "Pre-release channel. Not applied automatically.",
};

const POSTURE_TONE = {
  good: "border-emerald-400/40 bg-emerald-400/10 text-emerald-200",
  watch: "border-sky-400/40 bg-sky-400/10 text-sky-200",
  attention: "border-amber-400/40 bg-amber-400/10 text-amber-200",
} as const;

function DependencyHealthPage() {
  const report = useMemo(() => parseDependencyHealth(reportSource), []);
  const groups = useMemo(() => groupByBump(report.rows), [report.rows]);
  const posture = healthPosture(report);
  const percent = currentPercent(report);
  const age = reportAge(report.checkedAt);

  return (
    <div className="min-h-screen bg-[#0a0a0f] text-white">
      <header className="border-b border-white/5">
        <div className="mx-auto max-w-4xl px-6 py-16">
          <div className="mb-6 text-[10px] font-mono uppercase tracking-widest text-white/50">
            <AppLink to={ROUTES.home} className="hover:text-white">
              ← Back to Hub
            </AppLink>
          </div>
          <h1 className="text-4xl md:text-5xl font-semibold tracking-tight">
            Dependency Health
          </h1>
          <p className="mt-4 max-w-2xl text-white/70">
            Every dependency in the Resonance Hub is pinned to an exact version
            and checked against the npm <code className="rounded bg-white/10 px-1.5 py-0.5 font-mono text-[0.85em]">latest</code>{" "}
            release each week. This page renders that audit report verbatim —
            nothing here changes a pin.
          </p>

          <div
            className={`mt-8 rounded-lg border px-4 py-3 ${POSTURE_TONE[posture.tone]}`}
            role="status"
          >
            <div className="text-[10px] font-mono uppercase tracking-widest">
              {posture.label}
            </div>
            <p className="mt-1 text-sm text-white/80">{posture.detail}</p>
          </div>

          <dl className="mt-8 grid grid-cols-2 gap-3 sm:grid-cols-4">
            <Stat label="Pins audited" value={report.totalPins} />
            <Stat label="Up to date" value={`${report.currentCount} (${percent}%)`} />
            <Stat label="Behind" value={report.outdatedCount} />
            <Stat
              label="Report age"
              value={age ? age.label : "unknown"}
              muted
            />
          </dl>

          <div className="mt-6 flex flex-wrap gap-3 text-[10px] font-mono uppercase tracking-widest">
            <a
              href={`${REPO}/blob/main/reports/outdated-pins.md`}
              target="_blank"
              rel="noopener noreferrer"
              className="rounded border border-white/15 px-3 py-1.5 text-white/80 hover:border-white/40 hover:text-white"
            >
              Raw report
            </a>
            <a
              href={`${REPO}/blob/main/.github/workflows/outdated-pins.yml`}
              target="_blank"
              rel="noopener noreferrer"
              className="rounded border border-white/15 px-3 py-1.5 text-white/80 hover:border-white/40 hover:text-white"
            >
              Weekly audit workflow
            </a>
            <AppLink
              to={ROUTES.changelog}
              className="rounded border border-white/15 px-3 py-1.5 text-white/80 hover:border-white/40 hover:text-white"
            >
              Changelog
            </AppLink>
          </div>
        </div>
      </header>

      <main className="mx-auto max-w-4xl px-6 py-12 space-y-12">
        <section aria-labelledby="breakdown">
          <h2
            id="breakdown"
            className="border-b border-white/10 pb-3 text-2xl font-semibold tracking-tight"
          >
            How far behind
          </h2>
          {report.allCurrent ? (
            <p className="mt-4 text-white/70">
              Nothing is behind — all {report.totalPins} pins match the latest
              published release.
            </p>
          ) : (
            <ul className="mt-6 grid gap-3 sm:grid-cols-2">
              {groups.map((g) => (
                <li
                  key={g.bump}
                  className="rounded-lg border border-white/10 bg-white/[0.03] p-4"
                >
                  <div className="flex items-baseline justify-between gap-3">
                    <span
                      className={`rounded border px-2 py-0.5 text-[10px] font-mono uppercase tracking-widest ${BUMP_TONE[g.bump]}`}
                    >
                      {g.bump}
                    </span>
                    <span className="text-2xl font-semibold tabular-nums">
                      {g.rows.length}
                    </span>
                  </div>
                  <p className="mt-2 text-sm text-white/60">
                    {BUMP_BLURB[g.bump]}
                  </p>
                </li>
              ))}
            </ul>
          )}
        </section>

        {!report.allCurrent && (
          <section aria-labelledby="plan">
            <h2
              id="plan"
              className="border-b border-white/10 pb-3 text-2xl font-semibold tracking-tight"
            >
              Update plan
            </h2>
            {groups.map((g) => (
              <div key={g.bump} className="mt-8">
                <div className="mb-3 flex items-center gap-3">
                  <span
                    className={`rounded border px-2 py-0.5 text-[10px] font-mono uppercase tracking-widest ${BUMP_TONE[g.bump]}`}
                  >
                    {g.bump} · {g.rows.length}
                  </span>
                </div>
                <div className="overflow-x-auto rounded-lg border border-white/10">
                  <table className="w-full text-left text-sm">
                    <caption className="sr-only">
                      Pins with a new {g.bump} release, showing the pinned and
                      latest versions.
                    </caption>
                    <thead className="bg-white/[0.04] text-[10px] font-mono uppercase tracking-widest text-white/50">
                      <tr>
                        <th scope="col" className="px-4 py-2 font-normal">
                          Dependency
                        </th>
                        <th scope="col" className="px-4 py-2 font-normal">
                          Where
                        </th>
                        <th scope="col" className="px-4 py-2 font-normal">
                          Pinned
                        </th>
                        <th scope="col" className="px-4 py-2 font-normal">
                          Latest
                        </th>
                      </tr>
                    </thead>
                    <tbody className="divide-y divide-white/5">
                      {g.rows.map((r) => (
                        <tr key={`${r.section}:${r.name}`}>
                          <th
                            scope="row"
                            className="px-4 py-2 font-mono text-[0.8rem] font-normal text-white/90"
                          >
                            {r.name}
                          </th>
                          <td className="px-4 py-2 text-white/50">{r.section}</td>
                          <td className="px-4 py-2 font-mono text-[0.8rem] text-white/60 tabular-nums">
                            {r.pinned}
                          </td>
                          <td className="px-4 py-2 font-mono text-[0.8rem] text-white/90 tabular-nums">
                            {r.latest}
                          </td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>
              </div>
            ))}
          </section>
        )}

        <section aria-labelledby="how" className="text-white/70">
          <h2
            id="how"
            className="border-b border-white/10 pb-3 text-2xl font-semibold tracking-tight text-white"
          >
            How this works
          </h2>
          <ul className="mt-4 space-y-2 text-sm">
            <li>
              Pins are exact — no <code className="rounded bg-white/10 px-1 font-mono">^</code>{" "}
              or <code className="rounded bg-white/10 px-1 font-mono">~</code> ranges — and
              the build refuses to start if a pin drifts from the lockfile.
            </li>
            <li>
              The weekly audit only reports. Minor and patch bumps are gathered
              into a verified update pull request; majors stay for human review.
            </li>
            {report.notes.length > 0 && (
              <li className="text-white/50">{report.notes[report.notes.length - 1]}</li>
            )}
            {report.checkedAt && (
              <li className="text-white/50">
                Report generated{" "}
                <time dateTime={report.checkedAt}>{report.checkedAt}</time>.
              </li>
            )}
          </ul>
        </section>
      </main>

      <footer className="border-t border-white/5">
        <div className="mx-auto max-w-4xl px-6 py-10 text-[10px] font-mono uppercase tracking-widest text-white/50 flex flex-wrap justify-between gap-x-6 gap-y-2">
          <span>© {new Date().getFullYear()} The Resonance</span>
          <div className="flex gap-6">
            <AppLink to={ROUTES.governance} className="hover:text-white">
              Governance
            </AppLink>
            <AppLink to={ROUTES.changelog} className="hover:text-white">
              Changelog
            </AppLink>
            <a
              href={`${REPO}/blob/main/reports/outdated-pins.md`}
              target="_blank"
              rel="noopener noreferrer"
              className="hover:text-white"
            >
              Source
            </a>
          </div>
        </div>
      </footer>
    </div>
  );
}

function Stat({
  label,
  value,
  muted,
}: {
  label: string;
  value: string | number;
  muted?: boolean;
}) {
  return (
    <div className="rounded-lg border border-white/10 bg-white/[0.03] px-4 py-3">
      <dt className="text-[10px] font-mono uppercase tracking-widest text-white/50">
        {label}
      </dt>
      <dd
        className={`mt-1 text-xl font-semibold tabular-nums ${muted ? "text-white/70" : "text-white"}`}
      >
        {value}
      </dd>
    </div>
  );
}
