import { createFileRoute } from "@tanstack/react-router";
import { BackToHubHeader } from "@/components/BackToHubHeader";
import { AppLink } from "@/components/AppLink";
import { ROUTES } from "@/lib/routes";

export const Route = createFileRoute("/legal/terms")({
  head: () => ({
    meta: [
      { title: "Terms of use — Reson8.life" },
      {
        name: "description",
        content:
          "The terms that govern your use of the Reson8.life hub, its apps, credit wallets, and once-off packs.",
      },
      { property: "og:title", content: "Terms of use — Reson8.life" },
      {
        property: "og:description",
        content:
          "Account, packs, credits, acceptable use, refunds, and liability for Reson8.life.",
      },
      { property: "og:type", content: "article" },
      { name: "twitter:card", content: "summary" },
    ],
  }),
  component: TermsPage,
});

function TermsPage() {
  return (
    <div className="min-h-screen bg-background text-foreground">
      <BackToHubHeader />
      <main className="mx-auto max-w-3xl px-6 py-12 space-y-8">
        <header className="space-y-2">
          <p className="text-xs uppercase tracking-wide text-muted-foreground">Legal</p>
          <h1 className="text-3xl font-semibold tracking-tight">Terms of use</h1>
          <p className="text-sm text-muted-foreground">
            Effective from the date of your first sign-in or purchase.
          </p>
        </header>

        <section className="prose prose-sm dark:prose-invert max-w-none space-y-4">
          <h2>1. The agreement</h2>
          <p>
            By creating an account or purchasing a pack on Reson8.life you agree to these terms,
            the{" "}
            <AppLink to={ROUTES.legalPrivacy} className="underline">
              Privacy policy
            </AppLink>{" "}
            and the{" "}
            <AppLink to={ROUTES.governance} className="underline">
              Governance charter
            </AppLink>
            .
          </p>

          <h2>2. Your account</h2>
          <p>
            You are responsible for keeping your credentials safe and for activity that occurs
            under your account. Notify us immediately if you suspect unauthorised access.
          </p>

          <h2>3. Packs and credits</h2>
          <ul>
            <li>Packs are once-off purchases that grant a fixed number of credits to a specific spoke app.</li>
            <li>Credits are non-transferable between accounts and, unless stated otherwise on the pack, do not expire.</li>
            <li>We may retire or rename SKUs at any time — existing balances are preserved.</li>
          </ul>

          <h2>4. Acceptable use</h2>
          <p>You may not use the hub or its apps to:</p>
          <ul>
            <li>Break South African law or the laws of your jurisdiction.</li>
            <li>Generate material that sexualises minors, incites violence, or targets protected groups with hate speech.</li>
            <li>Probe, scrape, or overload the service, or bypass our rate limits and tier gates.</li>
            <li>Resell hub output as if it were a Reson8 product without our written consent.</li>
          </ul>

          <h2>5. Content ownership</h2>
          <p>
            You retain ownership of the material you upload. You grant us a worldwide, royalty-free
            licence to process it strictly to deliver the service. Output generated by an app on
            your behalf is yours to use, subject to the licence of the underlying model provider.
          </p>

          <h2>6. Refunds</h2>
          <p>
            Once-off packs are refundable within 7 days of purchase if you have not consumed more
            than 10% of the credits. Contact{" "}
            <a className="underline" href="mailto:billing@reson8.life">billing@reson8.life</a>{" "}
            with the invoice number. Refunds are processed via PayFast; entitlements are revoked
            on refund confirmation.
          </p>

          <h2>7. Availability</h2>
          <p>
            We aim for high uptime but do not guarantee that the service will be uninterrupted or
            error-free. Scheduled maintenance is announced on the{" "}
            <AppLink to={ROUTES.changelog} className="underline">
              changelog
            </AppLink>
            .
          </p>

          <h2>8. Liability</h2>
          <p>
            To the extent permitted by law, our aggregate liability for any claim arising out of
            these terms is limited to the amount you paid us in the 12 months before the event
            giving rise to the claim.
          </p>

          <h2>9. Termination</h2>
          <p>
            You may close your account at any time from the{" "}
            <AppLink to={ROUTES.accountPrivacy} className="underline">
              Privacy &amp; data
            </AppLink>{" "}
            page. We may suspend accounts that materially breach these terms, with notice where
            practical.
          </p>

          <h2>10. Changes</h2>
          <p>
            Material changes to these terms will be announced on the hub at least 14 days before
            they take effect.
          </p>

          <h2>11. Governing law</h2>
          <p>
            These terms are governed by the laws of the Republic of South Africa. Disputes are
            subject to the exclusive jurisdiction of the courts of the Western Cape.
          </p>
        </section>

        <footer className="border-t border-border pt-6 text-sm text-muted-foreground">
          See also{" "}
          <AppLink to={ROUTES.legalPrivacy} className="underline">
            Privacy
          </AppLink>{" "}
          ·{" "}
          <AppLink to={ROUTES.legalCookies} className="underline">
            Cookies
          </AppLink>
          .
        </footer>
      </main>
    </div>
  );
}
