// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from "@tanstack/react-start";
import { supabase } from "./client";

function hasSupabaseConfig(): boolean {
  const viteUrl = import.meta.env.VITE_SUPABASE_URL;
  const viteKey = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;
  const processUrl = typeof process !== "undefined" ? process.env.SUPABASE_URL : undefined;
  const processKey =
    typeof process !== "undefined" ? process.env.SUPABASE_PUBLISHABLE_KEY : undefined;
  return Boolean(viteUrl || processUrl) && Boolean(viteKey || processKey);
}

// Must be registered as a global `functionMiddleware` in `src/start.ts`; otherwise
// the browser never attaches the bearer token to serverFn RPCs. Public server functions
// must still work when Supabase is intentionally absent (for example CI smoke previews),
// so missing client configuration simply means "no bearer token to attach". Protected
// server functions remain enforced by the server-side `requireSupabaseAuth` middleware.
export const attachSupabaseAuth = createMiddleware({ type: "function" }).client(
  async ({ next }) => {
    if (!hasSupabaseConfig()) return next();
    const { data } = await supabase.auth.getSession();
    const token = data.session?.access_token;
    return next({
      headers: token ? { Authorization: `Bearer ${token}` } : {},
    });
  },
);
